# backend/Dockerfile
FROM gradle:8.13-jdk17 AS build

WORKDIR /app

# Copy build configuration
COPY build.gradle settings.gradle ./

# Copy source code
COPY src ./src

# add env variables
ARG MONGODB_URI
ENV MONGODB_URI=$MONGODB_URI

# Build the application
RUN gradle build --no-daemon

# Use a JRE-only image for the runtime stage
FROM eclipse-temurin:17-jre

WORKDIR /app

# Copy the built artifact from the build stage
COPY --from=build /app/build/libs/*.jar app.jar

ARG MONGODB_URI
ENV MONGODB_URI=$MONGODB_URI

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]