name: Trigger auto deployment for springboot-poc-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/springboot-poc-frontend-AutoDeployTrigger-176eeca2-506a-4b82-8ada-192d7456b299.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRINGBOOTPOCFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRINGBOOTPOCFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRINGBOOTPOCFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend/Dockerfile.prod
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.SPRINGBOOTPOCFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGBOOTPOCFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: springboot-poc-frontend
          resourceGroup: mploy
          imageToBuild: ghcr.io/springboot-poc-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


